//! Token export for the Mephistopheles design system (Phase P0+).
//!
//! Generates `tokens.css` (CSS variables in `:root`) from a `Palette`.
//! Mirrors the variable names already used in the existing Luna
//! frontend (e.g. `--bg`, `--text`, `--accent`, `--accent-strong`,
//! `--border`, `--bg-hover`, `--warn`, `--ok`, `--danger`) so
//! generated components drop into the existing shell without
//! requiring extra wiring.
//!
//! Note: `--accent-strong` is derived (lightened) from `accent`,
//! and `--border` is derived from `neutral_fg` with low opacity.
//! We use a tiny color-math helper for those derivations; no
//! external `image`/`palette` crate — just ratio blending.

use super::Palette;
use std::fmt::Write;

/// Build `tokens.css` content for the given palette. The output is
/// a self-contained `:root` block that can be imported from any
/// Svelte component or plain HTML page.
pub fn build_tokens_css(palette: &Palette) -> String {
    let accent_strong = lighten(&palette.accent, 0.12);
    let border = with_alpha(&palette.neutral_fg, 0.12);
    let bg_hover = lighten(&palette.neutral_bg, 0.06);

    let mut out = String::new();
    out.push_str("/* Auto-generated by DesignService — do not edit by hand. */\n");
    out.push_str("/* Source: <workspace>/.luna/design/palette.json (v");
    out.push_str(&palette.version.to_string());
    out.push_str(") */\n\n");
    out.push_str(":root {\n");

    // Primary brand
    writeln!(out, "  --primary:        {};", palette.primary).unwrap();
    writeln!(out, "  --secondary:      {};", palette.secondary).unwrap();
    writeln!(out, "  --accent:         {};", palette.accent).unwrap();
    writeln!(out, "  --accent-strong:  {};", accent_strong).unwrap();

    // Neutrals (background / foreground).
    writeln!(out, "  --bg:             {};", palette.neutral_bg).unwrap();
    writeln!(out, "  --bg-elevated:    {};", lighten(&palette.neutral_bg, 0.04)).unwrap();
    writeln!(out, "  --bg-hover:       {};", bg_hover).unwrap();
    writeln!(out, "  --text:           {};", palette.neutral_fg).unwrap();
    writeln!(out, "  --text-muted:     {};", with_alpha(&palette.neutral_fg, 0.65)).unwrap();
    writeln!(out, "  --text-inverse:   {};", palette.neutral_bg).unwrap();
    writeln!(out, "  --border:         {};", border).unwrap();

    // Semantic.
    writeln!(out, "  --ok:             {};", palette.semantic_ok).unwrap();
    writeln!(out, "  --warn:           {};", palette.semantic_warn).unwrap();
    writeln!(out, "  --danger:         {};", palette.semantic_err).unwrap();

    out.push_str("}\n");
    out
}

/// Lighten a hex color by `amount` in [0, 1]. Mixes the color
/// toward white. Returns a hex string in the same case as input.
fn lighten(hex: &str, amount: f32) -> String {
    let (r, g, b) = match parse_hex(hex) {
        Some(rgb) => rgb,
        None => return hex.to_string(),
    };
    let r = lerp(r, 255, amount);
    let g = lerp(g, 255, amount);
    let b = lerp(b, 255, amount);
    format_rgb(r, g, b)
}

/// Set the alpha channel of a hex color (or rgb). Returns an
/// `rgba(...)` string regardless of input format.
fn with_alpha(hex: &str, alpha: f32) -> String {
    let (r, g, b) = match parse_hex(hex) {
        Some(rgb) => rgb,
        None => return hex.to_string(),
    };
    format!("rgba({}, {}, {}, {:.2})", r, g, b, alpha)
}

fn parse_hex(hex: &str) -> Option<(u8, u8, u8)> {
    let s = hex.trim().trim_start_matches('#');
    if s.len() != 6 {
        return None;
    }
    let r = u8::from_str_radix(&s[0..2], 16).ok()?;
    let g = u8::from_str_radix(&s[2..4], 16).ok()?;
    let b = u8::from_str_radix(&s[4..6], 16).ok()?;
    Some((r, g, b))
}

fn lerp(a: u8, b: u8, t: f32) -> u8 {
    let a = a as f32;
    let b = b as f32;
    let v = a + (b - a) * t.clamp(0.0, 1.0);
    v.round().clamp(0.0, 255.0) as u8
}

fn format_rgb(r: u8, g: u8, b: u8) -> String {
    format!("#{:02x}{:02x}{:02x}", r, g, b)
}

// =====================================================================
// Tests
// =====================================================================

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn tokens_css_contains_all_variables() {
        let p = Palette::default();
        let css = build_tokens_css(&p);
        assert!(css.contains("--accent:"));
        assert!(css.contains("--bg:"));
        assert!(css.contains("--text:"));
        assert!(css.contains("--ok:"));
        assert!(css.contains("--warn:"));
        assert!(css.contains("--danger:"));
        assert!(css.contains("--border:"));
        assert!(css.contains("--bg-hover:"));
        assert!(css.contains("--accent-strong:"));
    }

    #[test]
    fn tokens_css_reflects_palette() {
        let mut p = Palette::default();
        p.accent = "#abcdef".into();
        let css = build_tokens_css(&p);
        assert!(css.contains("#abcdef"));
    }

    #[test]
    fn lighten_pushes_toward_white() {
        let lighter = lighten("#000000", 0.5);
        let (r, g, b) = parse_hex(&lighter).unwrap();
        assert!(r > 100 && g > 100 && b > 100);
    }

    #[test]
    fn with_alpha_uses_rgba() {
        let out = with_alpha("#ff0000", 0.5);
        assert_eq!(out, "rgba(255, 0, 0, 0.50)");
    }

    #[test]
    fn parse_hex_handles_invalid() {
        assert!(parse_hex("nope").is_none());
        assert!(parse_hex("#fff").is_none());
        assert!(parse_hex("#000000").is_some());
    }
}
